apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ui-deployment
  labels:
    app: flask-mysql-app

spec:
  selector:
    matchLabels:
      name: flask-app-pod
  replicas: 1
  template:
    metadata:
      name: flask-ui-pod
      labels:
        name: flask-app-pod
    spec:
      containers:
        - name: web-app
          image: thanandock/flask-mysql-app:1.0.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: env-config-app

